### ISSUE TITLE
SM8100 webos 5.20.15 not working

### ISSUE THREAD

**Issue by maoravi456** [RootMyTV/RootMyTV.github.io#50] opened 2022-05-28 23:39 UTC
Tried to root my TV(ver. 5.20.15) but nothing happens after root(stated as successful) - no new app

**Comment by rotdrop** [comment] 2022-07-10 08:08
#38

**Comment by DavidBuchanan314** [comment] 2022-08-16 10:47
Duplicate of #18

**Closed by DavidBuchanan314** 2022-08-16 10:47 UTC
