### ISSUE TITLE
Firmware 05.20.35 no homebrew install

### ISSUE THREAD

**Issue by navarayuk** [RootMyTV/RootMyTV.github.io#61] opened 2022-07-21 12:14 UTC
I know people have said a lower FW didn't work but wasn't sure on the TV models and I am on a newer version fw.
![IMG_20220721_131028598~2](https://user-images.githubusercontent.com/70470100/180210938-c7ea7f70-3a0b-4dbe-b9d8-4911173180a6.jpg)

Not sure oif this is a version that can be modded the about TV only has software fw version not web os version, I hope this will be supported on V3 if not please let me know thanks.

**Comment by navarayuk** [comment] 2022-07-21 15:59
> If you only need HomeBrew and not full root access then installing the Developer app (search LG's official app store, it's marked as educational), logging into it and enabling Dev Mode + Key Server, then using something like https://github.com/webosbrew/dev-manager-desktop with the 6 digit passphrase shown on screen will let you get HomeBrew installed along with other apps you might be looking for. Your IP address will be shown on the connections screen.

I would rather not have an account and this is a report saying it's not working telling me to use the official way to install apps is a fix and ask you kindly not to thanks, I don't agree with any TV needing a login or account no matter what your doing with it.

This was to help the Dev to show it does not work on this model of TV.

**Comment by DavidBuchanan314** [comment] 2022-08-16 10:45
Duplicate of #18

**Closed by DavidBuchanan314** 2022-08-16 10:45 UTC

**Comment by deniscerri** [comment] 2022-09-15 18:52
> If you only need HomeBrew and not full root access then installing the Developer app (search LG's official app store, it's marked as educational), logging into it and enabling Dev Mode + Key Server, then using something like https://github.com/webosbrew/dev-manager-desktop with the 6 digit passphrase shown on screen will let you get HomeBrew installed along with other apps you might be looking for. Your IP address will be shown on the connections screen.

Do i still have to periodically check the developer app?

**Comment by coolfizzin** [comment] 2022-09-16 13:59
@deniscerri Download dev-desktop-manager and use it to connect to your TV in developer mode. The app has a section that explains how to use IFTTT to automatically renew the developer mode. It's not 100% guaranteed to work every time, but it's reliable enough for now.
